---
title: "R Notebook"
output: html_notebook
---



### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/Proteomics_virus/")) 
```


```{r}
library(xlsx)
library(dplyr)
```


## check overlap 
```{r}
munch_DGE <- read.xlsx("/home/flomik/Desktop/Code-PHD/Corona_projects/Corona_omics/results/Munch/DGE/Corona_munch_UNIF24_vs_H24PI_DGE_results_filt.xlsx",1)
```

```{r}
caco2_DGE <- read.xlsx("/home/flomik/Desktop/Code-PHD/Proteomics_virus/results/Caco2/DGE/Caco2_R2_Caco2_U_vs_R2_Caco2_T_DGE_results_filt.xlsx",1)
```

## filtering

```{r}
munch_DGE$Accession <- gsub(";.*", "", munch_DGE$Accession)
munch_DGE$Accession[12] <- "P05787"
```
```{r}
munch_DGE$Gene_name <- gsub(";.*", "", munch_DGE$Gene_name)
```

```{r}
munch_DGE <- munch_DGE[!is.na(munch_DGE$Gene_name),]
```

```{r}
length(munch_DGE$Gene_name[munch_DGE$Gene_name %in% caco2_DGE$Gene_name])
```
```{r}
length(munch_DGE$Accession[munch_DGE$Accession %in% caco2_DGE$Accession])
```
```{r}
#write.xlsx(munch_DGE, file = "overlap_caco2_munch.xlsx", sheetName="Munch all", append=TRUE)
#write.xlsx(caco2_DGE, file = "overlap_caco2_munch.xlsx", sheetName="Caco2 all", append=TRUE)
#write.xlsx(munch_DGE[munch_DGE$logFC > 0, ], file = "overlap_caco2_munch.xlsx", sheetName="Munch up", append=TRUE)
#write.xlsx(munch_DGE[munch_DGE$logFC < 0, ], file = "overlap_caco2_munch.xlsx", sheetName="Munch down", append=TRUE)
#write.xlsx(caco2_DGE[caco2_DGE$logFC > 0, ], file = "overlap_caco2_munch.xlsx", sheetName="Caco2 up", append=TRUE)
#write.xlsx(caco2_DGE[caco2_DGE$logFC < 0, ], file = "overlap_caco2_munch.xlsx", sheetName="Caco2 down", append=TRUE)
```

```{r}
write.csv(munch_DGE, "processing/Munch_clean_DGE.csv")
write.csv(caco2_DGE, "processing/Caco2_clean_DGE.csv")
```

## heatmap overlap caco2 / Munch

```{r}
overlap_data <- munch_DGE$Gene_name[munch_DGE$Gene_name %in% caco2_DGE$Gene_name]
```

```{r}
input <- read.xlsx("/home/flomik/Desktop/Code-PHD/Proteomics_virus/data/Munch/data/Supplementary Table 02.xlsx", 2)
input <- input[,c(1:26)]
```

```{r}
input$UniProt.Accession <- gsub(";.*", "", input$UniProt.Accession)
input$Gene.Symbol <- gsub(";.*", "", input$Gene.Symbol)
```

```{r}
caco <- read.delim("/home/flomik/Desktop/Code-PHD/Proteomics_virus/processing/norm_files/Caco2_norm_file.txt")
```

```{r}
names(caco)[1] <- "UniProt.Accession"
```

```{r}
data <- merge(input, caco, by = "UniProt.Accession")
```

```{r}
data <- data[data$Gene.Symbol %in% overlap_data,]

data <- data[!duplicated(data$Gene.Symbol),]
```
```{r}
rownames(data) <- data$Gene.Symbol
```

```{r}
overlap_data[!overlap_data %in% data$Gene_name]
```

```{r}
data_munch <- data[,c(2, 3:26)]
data_caco <- data[,c(2, 27:32)]
```

```{r}
library(circlize)
library(ComplexHeatmap)
col_fun_2 = colorRamp2(c(-1.5,  - 0.001 ,0,  0.001, 1.5), c("blue", "#b3ccff","white","#ff9999", "red"))
col_fun1 = colorRamp2(c(-2,-1,-0.5, 0,0.5,1,2), c("#7F7F00","#B2B200" ,"#E5E500","white","#BF7FBF","#993299","#590059"))
#col_fun = colorRamp2(c(-2, 0, 2), c("green", "white", "red"))
```
```{r}
c_t0 <- "#B1A78C"
c_t24 <- "#687E8A"
c_t48 <- "#41607D"
c_t72 <- "#09253B"
```


```{r}
nb_samples <- 3

# define conditions
t2_U <- "UNIF02"
t6_U <- "UNIF06"
t10_U <- "UNIF10"
t24_U <- "UNIF24"

t2_I <- "H02PI"
t6_I <- "H06PI"
t10_I <- "H10PI"
t24_I <- "H24PI"
```

```{r}
condition <- as.factor(c(rep(t2_U, nb_samples), rep(t6_U , nb_samples),
                         rep(t10_U, nb_samples), rep(t24_U , nb_samples),
                         rep(t2_I, nb_samples), rep(t6_I, nb_samples),
                         rep(t10_I, nb_samples), rep(t24_I, nb_samples)))
```

```{r}
condition <- factor(condition, levels = c("UNIF02", "UNIF06", "UNIF10", "UNIF24", "H02PI", "H06PI", "H10PI", "H24PI"))
```


## DGE
```{r}
h2 <- read.xlsx("/home/flomik/Desktop/Code-PHD/Corona_projects/INF_Grant/data/Munch/DGE/Corona_munch_UNIF02_vs_H02PI_DGE_results_filt.xlsx", 1)
h6 <- read.xlsx("/home/flomik/Desktop/Code-PHD/Corona_projects/INF_Grant/data/Munch/DGE/Corona_munch_UNIF06_vs_H06PI_DGE_results_filt.xlsx", 1)
h10 <- read.xlsx("/home/flomik/Desktop/Code-PHD/Corona_projects/INF_Grant/data/Munch/DGE/Corona_munch_UNIF10_vs_H10PI_DGE_results_filt.xlsx", 1)
h24 <- read.xlsx("/home/flomik/Desktop/Code-PHD/Corona_projects/INF_Grant/data/Munch/DGE/Corona_munch_UNIF24_vs_H24PI_DGE_results_filt.xlsx", 1)
h2_24_inf <- read.xlsx("/home/flomik/Desktop/Code-PHD/Corona_projects/INF_Grant/data/Munch/DGE/Corona_munch_H02PI_vs_H24PI_DGE_results_filt.xlsx", 1)
```

```{r}
h2 <- h2[h2$Gene_name %in% overlap_data,]
h2 <- select(h2, Gene_name, logFC)
names(h2)[2] <- "LF_h2"

h6 <- h6[h6$Gene_name %in% overlap_data,]
h6 <- select(h6, Gene_name, logFC)
names(h6)[2] <- "LF_h6"

h10 <- h10[h10$Gene_name %in% overlap_data,]
h10 <- select(h10, Gene_name, logFC)
names(h10)[2] <- "LF_h10"

h24 <- h24[h24$Gene_name %in% overlap_data,]
h24 <- select(h24, Gene_name, logFC)
names(h24)[2] <- "LF_h24"

h2_24_inf <- h2_24_inf[h2_24_inf$Gene_name %in% overlap_data,]
h2_24_inf <- select(h2_24_inf, Gene_name, logFC)
names(h2_24_inf)[2] <- "LF_h2_24_inf"
```
```{r}
names(data_munch)
```

```{r}
names(data_munch)[1] <- "Gene_name"
data_munch <- merge(data_munch, h2, by = "Gene_name", all.x = TRUE)
data_munch <- merge(data_munch, h6, by = "Gene_name", all.x = TRUE)
data_munch <- merge(data_munch, h10, by = "Gene_name", all.x = TRUE)
data_munch <- merge(data_munch, h24, by = "Gene_name", all.x = TRUE)
data_munch <- merge(data_munch, h2_24_inf, by = "Gene_name", all.x = TRUE)
```

```{r}
names(data_munch)
```

```{r}
data_munch[,c(2:25)] <- data.frame(t(scale(t(data_munch[,c(2:25)]))))
```
```{r}
rownames(data_munch) <- data_munch$Gene_name
```

```{r}
#data_munch[,c(2:25)] <- data_munch[,c(2:25)]*-1
```


```{r}
pdf("results/figures/overlap_caco_munch_MUNCH.pdf", width = 12, height = 8)
ht = Heatmap(data_munch[,c(2:25)],
             col = col_fun1,
             column_order = sort(colnames(data_munch[,c(2:25)])),
             show_column_names = FALSE,
             column_split = condition,
             column_title = unique(condition),
             column_title_gp = gpar(fill = c(rep("white", 4), c_t0, c_t24, c_t48, c_t72)),
             border = FALSE, 
             column_gap = unit(2, "mm"),
             right_annotation = rowAnnotation(H2 = data_munch$LF_h2,
                                              H6 = data_munch$LF_h6, 
                                              H10 = data_munch$LF_h10, 
                                              H24 = data_munch$LF_h24,
                                              H2_24inf = data_munch$LF_h2_24_inf,
                                              col = list(H2 = col_fun_2,
                                                         H6 = col_fun_2,
                                                         H10 = col_fun_2,
                                                         H24 = col_fun_2,
                                                         H2_24inf = col_fun_2), show_legend = TRUE, gp = gpar(col = "grey"))
             
             )

ht
dev.off()
```


## heatmap


```{r}
data_caco <- data_caco[,c(1, 2, 4, 6, 3, 5, 7)]
names(data_caco)[1] <- "Gene_name"
```

```{r}
caco2_DGE <- read.xlsx("/home/flomik/Desktop/Code-PHD/Proteomics_virus/results/Caco2/DGE/Caco2_R2_Caco2_U_vs_R2_Caco2_T_DGE_results.xlsx", 1)
caco2_DGE$logFC <- ifelse(caco2_DGE$adj.P.Val < 0.05, caco2_DGE$logFC, NA)
```



```{r}
caco2_DGE <- select(caco2_DGE, Gene_name, logFC, adj.P.Val)
```
```{r}
data <- merge(data_caco, caco2_DGE, by = "Gene_name")
```

```{r}
data[,c(2:7)] <- data.frame(t(scale(t(data[,c(2:7)]))))
```
```{r}
rownames(data) <- data$Gene_name
```

```{r}
condition <- c(rep("Mock", 3), rep("24hpi", 3))
```


```{r}
col_fun1 = colorRamp2(c(-2,-1,-0.5, 0,0.5,1,2), c("#7F7F00","#B2B200" ,"#E5E500","white","#BF7FBF","#993299","#590059"))
```
```{r}
data[,c(2:7)] <- data[,c(2:7)]*-1
```

```{r}
pdf("results/figures/overlap_caco_munch_CACO2.pdf", width = 5, height = 8)
ht = Heatmap(data[,c(2:7)],
             col = col_fun1,
             column_order = sort(colnames(data[,c(2:7)])),
             show_column_names = FALSE,
             column_split = condition,
             column_title = unique(condition),
             column_title_gp = gpar(fill = c("#A97A03","#ffdfba")),
             border = FALSE, 
             column_gap = unit(2, "mm"),
             heatmap_legend_param = list(
        title = "z-score", at = c(-2, 0, 2), 
        labels = c("-2", "0", "2"), col_fun = col_fun1
    ),
             right_annotation = rowAnnotation(logFC = data$logFC,
                                              col = list(logFC = col_fun_2),
                                              show_legend = TRUE, gp = gpar(col = "grey"))
             
             )

ht
dev.off()
```


